name: Test caching

on:
  workflow_dispatch:

jobs:
  render-tutorials:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    name: ${{ matrix.config.r }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: '4.3.3' }
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Restore HTML cache
        uses: actions/cache@v4
        with:
          path: tmp-code
          key: html-cache-${{ hashFiles('tmp-code/*.html') }}
          
      - name: Restore HTML files to .code directory
        run: |
          echo "Contents of the .code directory before copy"
          ls -la .code
          if [ -d tmp-code ]; then
            echo "Contents of the tmp-code directory"
            ls -la tmp-code
            cp -p tmp-code/*.html .code/
            echo "Contents of the .code directory after copy"
            ls -la .code
          else
            echo "No previously rendered HTML files found. Skipping restore."
          fi
          
      - name: fake make
        run: |
          cp .code/bglm_example1.qmd .code/bglm_example1.html

      - name: copy html files
        run: |
          cp -p .code/*.html tmp-code
