name: Render and publish the tutorials

on:
  workflow_dispatch:
#  pull_request:
  push:
    branches: ['AIMS@JCU2025']

jobs:
  render-tutorials:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    name: ${{ matrix.config.r }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: '4.3.3' }
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # ensure that more than the last commit is checked out so that we can get time stamps
      # Restore the timestamps - I am going to try to use these to work out what is new and what is not    
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1